import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  console.log("🚀 Deploying DataContract to Chiado Testnet...");
  console.log("=================================================");

  // Get the contract factory
  const DataContract = await ethers.getContractFactory("DataContract");

  // Get the deployer account
  const [deployer] = await ethers.getSigners();
  console.log("Deploying with account:", deployer.address);

  // Check balance
  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("Account balance:", ethers.formatEther(balance), "xDAI");

  if (balance === 0n) {
    console.error("❌ Insufficient balance! Please fund your account with Chiado xDAI.");
    console.log("Get Chiado xDAI from:");
    console.log("- Chiado Faucet: https://gnosisfaucet.com/");
    process.exit(1);
  }

  // Deploy the contract
  console.log("\n📋 Deploying contract...");
  const contract = await DataContract.deploy();
  
  // Wait for deployment transaction to be mined
  console.log("⏳ Waiting for deployment transaction...");
  await contract.waitForDeployment();
  
  const contractAddress = await contract.getAddress();
  console.log("✅ DataContract deployed to:", contractAddress);

  // Get deployment transaction details
  const deploymentTx = contract.deploymentTransaction();
  if (deploymentTx) {
    console.log("Transaction hash:", deploymentTx.hash);
    console.log("Block number:", deploymentTx.blockNumber);
    console.log("Gas used:", deploymentTx.gasLimit?.toString());
  }

  // Verify the contract is deployed correctly
  console.log("\n🔍 Verifying deployment...");
  console.log("Contract deployed successfully - public access enabled");
  console.log("Anyone can call sendDataToTarget function");

  // Create deployments directory if it doesn't exist
  const deploymentsDir = path.join(__dirname, "..", "deployments");
  if (!fs.existsSync(deploymentsDir)) {
    fs.mkdirSync(deploymentsDir, { recursive: true });
  }

  // Save deployment information
  const deploymentInfo = {
    network: "chiado",
    chainId: 10200,
    contractName: "DataContract",
    contractAddress: contractAddress,
    deployerAddress: deployer.address,
    transactionHash: deploymentTx?.hash,
    blockNumber: deploymentTx?.blockNumber,
    gasUsed: deploymentTx?.gasLimit?.toString(),
    timestamp: new Date().toISOString(),
    rpcUrl: process.env.CHIADO_RPC_URL || "https://rpc.chiadochain.net"
  };

  // Write deployment JSON
  const deploymentFile = path.join(deploymentsDir, "chiado-deployment.json");
  try {
    fs.writeFileSync(deploymentFile, JSON.stringify(deploymentInfo, null, 2));
    console.log("✅ Deployment info saved to:", deploymentFile);
  } catch (error) {
    console.error("❌ Failed to save deployment info:", error);
  }

  // Generate environment variables file
  const envContent = `# Chiado Testnet Deployment Configuration
# Generated on ${new Date().toISOString()}

CHIADO_CONTRACT_ADDRESS=${contractAddress}
CHIADO_DEPLOYER_ADDRESS=${deployer.address}
CHIADO_CHAIN_ID=10200
CHIADO_RPC_URL=${process.env.CHIADO_RPC_URL || "https://rpc.chiadochain.net"}
CHIADO_BLOCK_EXPLORER=https://gnosis-chiado.blockscout.com
`;

  const envFile = path.join(deploymentsDir, "chiado.env");
  try {
    fs.writeFileSync(envFile, envContent);
    console.log("✅ Environment variables saved to:", envFile);
  } catch (error) {
    console.error("❌ Failed to save environment file:", error);
  }

  // Generate Go constants file
  const goContent = `// Code generated by Chiado deployment script. DO NOT EDIT.
// Generated on ${new Date().toISOString()}

package main

const (
	// Chiado Testnet Configuration
	ChiadoChainID      = 10200
	ChiadoRPCURL       = "${process.env.CHIADO_RPC_URL || "https://rpc.chiadochain.net"}"
	ChiadoExplorerURL  = "https://gnosis-chiado.blockscout.com"
	
	// Contract Deployment Info
	ChiadoContractAddress = "${contractAddress}"
	ChiadoDeployerAddress = "${deployer.address}"
	ChiadoDeploymentBlock = ${deploymentTx?.blockNumber || 0}
)
`;

  const goFile = path.join(deploymentsDir, "chiado-constants.go");
  try {
    fs.writeFileSync(goFile, goContent);
    console.log("✅ Go constants saved to:", goFile);
  } catch (error) {
    console.error("❌ Failed to save Go constants:", error);
  }

  console.log("\n🎉 Deployment completed successfully!");
  console.log("=======================================");
  console.log("Contract Address:", contractAddress);
  console.log("Network: Chiado Testnet (Chain ID: 10200)");
  console.log("Explorer:", `https://gnosis-chiado.blockscout.com/address/${contractAddress}`);
  console.log("Public Access: Enabled (anyone can call functions)");
  
  console.log("\n📋 Next steps:");
  console.log("1. Test contract interaction");
  console.log("2. Deploy to Gnosis mainnet when ready");
  console.log("3. Bridge more xDAI if needed");
  
  console.log("\n🔗 Useful links:");
  console.log("- Chiado Faucet: https://gnosisfaucet.com/");
  console.log("- Chiado Explorer: https://gnosis-chiado.blockscout.com/");
  console.log("- Gnosis Chain Docs: https://docs.gnosischain.com/");
}

// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main().catch((error) => {
  console.error("❌ Deployment failed:", error);
  process.exitCode = 1;
});
