// Code generated by Gnosis deployment script. DO NOT EDIT.
// Generated on 2025-06-14T13:09:38.610Z

package main

const (
	// Gnosis Chain Configuration
	GnosisChainID      = 100
	GnosisRPCURL       = "https://rpc.gnosischain.com"
	GnosisExplorerURL  = "https://gnosisscan.io"
	
	// Contract Deployment Info
	GnosisContractAddress = "0x8946CCb5176E614F342157139c7546DA81085E6f"
	GnosisDeployerAddress = "0x4650CaeF79E7B72FFe1dEa45e5CdA96376cc02f9"
	GnosisDeploymentBlock = 40580477
)
